### ISSUE TITLE
Audio playback issues with fast forward

### ISSUE THREAD

**Issue by Aztorius** [marlam/bino#15]
Hi, i'm running Fedora 37 (KDE Wayland + Pipewire + mesa with RX 6700) with Bino 2.0 manually compiled (thanks for this great 3D video software).

I'm playing an MKV file (3D Half Side By Side) of 13GB :
![image](https://user-images.githubusercontent.com/6351814/204358703-36777893-2b43-46e7-9aaa-654e2d12ccd1.png)

When using multiple times the Right arrow to move forward (or page up), the sound is desynchronising and then totally mute.
Then, if I try to change Audio track Bino completely freeze.
Also the sound briefly spikes at the start of the video (really spikes).

Thanks.

**Comment by marlam** [comment]
Since version 2.0, Bino does not implement its own decoding, seeking or audio/video synchronization anymore. It relies on Qt Multimedia instead. So this is most probably an issue with Qt Multimedia; either its implementation or its backend (GStreamer).
Maybe adding seeking support to the [Qt Media Player example](https://doc.qt.io/qt-6/qtmultimedia-player-example.html) via [`QMediaPlayer::setPosition()`](https://doc.qt.io/qt-6/qmediaplayer.html#position-prop) could help you track down the problem.
There's nothing we can do to fix this in Bino.

**Comment by Aztorius** [comment]
I've just compiled the Qt Media Player example. Same issues (without the audio spike at the beginning like Bino). When seeking further in the file a first time it is fine, but the second time audio is muted, then the app freeze if I try to change audio track. Same issues with different video files. No useful logs.

**Comment by marlam** [comment]
That should be enough material to write a [Qt bug report](https://bugreports.qt.io/secure/Dashboard.jspa).

**Comment by marlam** [comment]
Closing this since it is a Qt problem, not a Bino problem.
