### ISSUE TITLE
Save 3D modes settings

### ISSUE THREAD

**Issue by brunetton** [marlam/bino#18]
Hi ! First of all, thank you a LOT for this wonderful piece of software ! I'm using it a lot and really love it !

Those days I'm re-compressing 3D videos I made and I use Bino to check outputs of different Handbrake compression settings. So I'm using Bino a lot to check 30 second videos. But Bino doesn't actually remember my last 3D settings: everytime I check a test clip I've to set:

- 3D modes -> input 3D SBS -> input left/right half
- 3D modes -> output 2D left

This is a quite time-consuming process to set all of those settings each time.

I'd like to:
- Bino remember my last settings
- or better (in a second time I suppose): being able to save 3D settings as presets, and reopen them later (for example here my preset is "HSBS -> left only", but I'm also using a lot "HSBS -> anaglyph" and sometimes "Surround 360 -> anaglyph")

Thanks !

Bino 2.1 / flatpak / Ubuntu 22.04

**Comment by brunetton** [comment]
**Workaround**: use command line

     bino -i left-right-half -o left myfile.mkv

(`bino --help for all possible values`)

In my case (using flatpak, as Bino is not packaged in Debian format anymore):

     /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=bino --file-forwarding org.bino3d.bino -i left-right-half -o left myfile.mkv

**Comment by marlam** [comment]
Yes I agree that Bino should remember some settings, at least the preferred 3D output mode.
This is not yet implemented because I'm not sure about what should be remembered and what should not.
In retrospect I don't like the approach of Bino-1.6.x, so I would like to improve things with Bino 2.x, but I'm not sure how yet.

Remembering an input mode does not make sense since it depends on the video file. Unfortunately Qt does not yet support reading stereoscopic or surround metadata. And remembering an input mode for each file, like Bino-1.6.x did, does not seem right either.

The `-o left` is a good workaround for the output mode. Maybe it would be an option for you to use the [filename conventions](https://bino3d.org/bino-manual.html#file-name-conventions) to tell Bino about the correct input mode?

**Comment by brunetton** [comment]
> Yes I agree that Bino should remember some settings, at least the preferred 3D output mode. This is not yet implemented because I'm not sure about what should be remembered and what should not. In retrospect I don't like the approach of Bino-1.6.x, so I would like to improve things with Bino 2.x, but I'm not sure how yet.
> 
> Remembering an input mode does not make sense since it depends on the video file. Unfortunately Qt does not yet support reading stereoscopic or surround metadata. And remembering an input mode for each file, like Bino-1.6.x did, does not seem right either.

I agree,

> 
> The `-o left` is a good workaround for the output mode. Maybe it would be an option for you to use the [filename conventions](https://bino3d.org/bino-manual.html#file-name-conventions) to tell Bino about the correct input mode?

Good to know :tada: I didn't knew it ! This is a precious information ! I think this should be highlighted from the README, this is not obvious IMHO that this doc exists when going to the project from Github. I'll make a PR for that !

Anyway thanks for Bino !

**Comment by marlam** [comment]
I'll close this issue for now since we have a workaround. A general solution for remembering settings is still on the TODO list.
